image:
  name: donaldrich/hashicorp:packer
#  entrypoint:
#    - '/usr/bin/env'
#    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - packer --version

stages:
  - validate
  - build
  - test
  - deploy

validate:
  stage: validate
  script:
    - packer validate $PACKERFILE
 #   - find . -maxdepth 1 -name '*.json' -print0 | xargs -t0n1 packer validate

build:
  stage: deploy
  environment: production
  script:
    - packer build $PACKERFILE
#    - find . -maxdepth 1 -name '*.json' -print0 | xargs -t0n1 packer build
  when: manual
  only:
    - master