image:
  name: donaldrich/terraform:latest
  entrypoint: [""]

before_script:
  - rm -rf .terraform
  - terraform --version
  #   - mkdir -p ./creds
  #   - echo "creds" | base64 -d > ./creds/serviceaccount.json
  - terraform init

stages:
  # - init
  - validate
  - plan
  - apply
  - destroy

# init:
#   stage: init
#   script:
#     - terraform init

validate:
  stage: validate
  # dependencies:
  #   - init
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -auto-approve "planfile"
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  dependencies:
    - apply
  when: manual
