image:
  name: donaldrich/terraform:latest
  entrypoint: [""]
#   entrypoint:
#     - '/usr/bin/env'
#     - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  - terraform --version
#   - mkdir -p ./creds
#   - echo "creds" | base64 -d > ./creds/serviceaccount.json
  - terraform init $TERRAFORM_PATH

stages:
  # - init
  - validate
  - plan
  - apply
  - destroy

# init:
#   stage: init
#   script:
#     - terraform init

validate:
  stage: validate
  # dependencies:
  #   - init
  script:
    - terraform validate $TERRAFORM_PATH

plan:
  stage: plan
  script:
    - terraform plan -out "planfile" $TERRAFORM_PATH
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -auto-approve "planfile" $TERRAFORM_PATH
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve $TERRAFORM_PATH
  dependencies:
    - apply
  when: manual