pages:
  stage: documentation
  image:
    name: donaldrich/mkdocs:latest
    entrypoint: [""]
  before_script:
    - rm -r public || echo "public doesn't exist"
    - rm docs/about/LICENCE || true
    - rm docs/about/CHANGELOG || true
    - cp LICENCE /docs/about
    - cp CHANGELOG /docs/about
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  rules:
    - exists:
        - mkdocs.yml
      changes:
        - "docs/**/*"
        - "docs/*"
        - "mkdocs.yml"
      when: always
    - when: never

file-tree-pages:
  image:
    name: donaldrich/mkdocs:latest
    entrypoint: [""]
  stage: build
  script:
    - mkdir -p .meta/snippets || echo "snippet dir already exists"
    - tree --dirsfirst -I docs > .meta/snippets/layout.md
  rules:
    - exists:
        - mkdocs.yml
      changes:
        - "docs/**/*"
        - "docs/*"
        - "mkdocs.yml"
      when: always
    - when: never
