pages:
  stage: .post
  image:
    name: donaldrich/mkdocs:latest
    entrypoint: [""]
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  cache:
    untracked: true
    paths:
    - doc-test/
  rules:
    - exists:
      - "mkdocs.yml"
      when: on_success
    - when: never
