pages:
  stage: documentation
  image:
    name: donaldrich/mkdocs:latest
    entrypoint: [""]
  script:
  - mkdocs build
  - rm -r site/snippets || true
  - mv site public
  artifacts:
    paths:
    - public
  rules:
    - exists:
      - mkdocs.yml
      when: always
    - when: never

file-tree-pages:
  image:
    name: donaldrich/function:tree
    entrypoint: [""]
  stage: build
  # variables:
  #   GIT_STRATEGY: clone
  script:
    - mkdir -p docs/snippets || echo "snippet dir already exists"
    - tree --dirsfirst -I docs > docs/snippets/layout.md
  rules:
    - exists:
      - mkdocs.yml
      when: always
    - when: never