pages:
  stage: documentation
  image:
    name: donaldrich/mkdocs:latest
    entrypoint: [""]
  before_script:
    - rm -r public || echo "public doesn't exist"
    - rm docs/about/LICENCE || echo "public doesn't exist"
    - rm docs/about/CHANGELOG || echo "public doesn't exist"
    - cp LICENCE /docs/about || echo "public doesn't exist"
    - cp CHANGELOG /docs/about || echo "public doesn't exist"
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  rules:
    - exists:
        - mkdocs.yml
      changes:
        - "docs/**/*"
        - "docs/*"
        - "mkdocs.yml"
      when: always
    - when: never

    