pages:
  stage: documentation
  image:
    name: donaldrich/mkdocs:latest
    entrypoint: [""]
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  rules:
    - exists:
      - "mkdocs.yml"
      when: always
    - when: never
