pages:
  stage: .post
  image:
    name: donaldrich/mkdocs:latest
    entrypoint: [""]
  script:
  - rm -r site
  - rm -r public
  - mkdocs build
  - mv -R site public
  # - cp site public
  artifacts:
    paths:
    - public
  # cache:
  #   untracked: true
  #   paths:
  #   - doc-test/
  rules:
    - exists:
      - "mkdocs.yml"
      when: on_success
    - when: never
