pages:
  stage: .post
  image:
    name: donaldrich/mkdocs:latest
    entrypoint: [""]
  # before_script:
  # - rm -r site
  # - rm -r public
  script:
  - mkdocs build
  - mv site public
  # - cp site public
  artifacts:
    paths:
    - public
  rules:
    - exists:
      - "mkdocs.yml"
      when: always
    - when: never
