pages:
  stage: documentation
  image:
    name: donaldrich/mkdocs:latest
    entrypoint: [""]
  before_script:
    - rm -r public
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
    - public
  rules:
    - exists:
      - mkdocs.yml
      changes:
      - "docs/**/*"
      - "docs/*"
      when: always
    - when: never

file-tree-pages:
  image:
    name: donaldrich/mkdocs:latest
    entrypoint: [""]
  stage: build
  script:
    - mkdir -p .meta/snippets || echo "snippet dir already exists"
    - tree --dirsfirst -I docs > .meta/snippets/layout.md
  rules:
    - exists:
      - mkdocs.yml
      changes:
      - "docs/**/*"
      - "docs/*"
      when: always
    - when: never