include:
  - project: donaldrich/modular-gitlab-ci
    file: function/ansible/runner.yml

ansible:site-yml:
  extends: .ansible-runner
  stage: run
  script:
    - ansible-playbook -vvv site.yml
  resource_group: production
  allow_failure: true
  variables:
    ANSIBLE_DEBUG: "1"
  # retry: 2
  artifacts:
    paths:
      - ansible.log
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - when: on_success
