include:
  - project: donaldrich/modular-gitlab-ci
    file: function/ansible/runner.yml

ansible:run-site-yml:
  extends: .ansible-runner
  stage: run
  script:
    - tusk site
  resource_group: production
  variables:
    ANSIBLE_CALLBACK_PLUGINS: "$(python3 -m ara.setup.callback_plugins)"
    ARA_API_CLIENT: "http"
    ARA_API_SERVER: "http://192.168.1.101:8734"
  # allow_failure: true
  # retry: 2
  # artifacts:
  #   paths:
  #     - ansible.log
  rules:
    - if: '$DEBUG_ANSIBLE == "true"'
      when: never
    # - if: '$CI_PIPELINE_SOURCE == "pipeline"'
    #   when: never
    - when: on_success

ansible:site-yml-debug:
  extends: .ansible-runner
  stage: run
  script:
    - ansible-playbook $ANSIBLE_PREFIX site.yml
  variables:
    ANSIBLE_DEBUG: "1"
  resource_group: production
  # allow_failure: true
  # retry: 2
  # artifacts:
  #   paths:
  #     - ansible.log
  rules:
    - if: '$DEBUG_ANSIBLE == "true"'
      variables:
        ANSIBLE_DEBUG: "1"
        ANSIBLE_PREFIX: "-vvv"
      when: on_success
    # - if: '$CI_PIPELINE_SOURCE == "pipeline"'
    #   when: never
    - when: never
