.ssh-provision: &ssh-provision
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@$SECRET_REPO ~/secrets
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - cp -r ~/secrets/ssh/. ~/.ssh
  - sudo chmod 0600 -R ~/.ssh
  - sudo chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

.ansible-runner:
  image:
    name: donaldrich/ansible:latest
    entrypoint: [""]
  before_script:
    - *ssh-provision
  after_script:
    - rm -r ~/secrets || true
    - rm -r ~/.ssh || true
  # artifacts:
  #   name: "$CI_JOB_NAME log"
  #   when: always
  #   paths:
  #     - $CI_PROJECT_DIR/ansible.log
  variables:
    ANSIBLE_CONFIG: "ansible.cfg"
    ANSIBLE_LOG_PATH: "${CI_PROJECT_DIR}/ansible.log"
    # ANSIBLE_HOST_KEY_CHECKING: "false"
    # ANSIBLE_RETRY_FILES_ENABLED: "false"
    # ANSIBLE_FORCE_COLOR: "true"
    #    ANSIBLE_VAULT_PASSWORD_FILE: ./vault.key
