include:
  # - local: '/function/analysis/sast.yml'
  - local: '/function/notifications/healthchecks/repo-ci-pipeline.yml'
  - local: '/function/notifications/pushover/repo-ci-pipeline.yml'
  # - local: '/function/lint/default.yml'
  # - local: '/function/docker/default.yml'
  - local: '/function/documentation/mkdocs.yml'
  # - local: '/function/documentation/pdf.yml'

variables:
  PUSHOVER_ID: $CI_PROJECT_TITLE

stages:
  - debug
  - lint
  - build
  - deploy
  - notify


