include:
  - local: templates/default.yml
  - local: function/repo/semantic-release.yml
  # - local: goss-test.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/analysis/secrets/default.yml
variables:
  PUSHOVER_ID: $CI_PROJECT_TITLE
  DISABLE_SAST: "true"
  DISABLE_LINTING: "true"
  DISABLE_HEALTHCHECKS: "true"

stages:
  - .pre
  - debug
  - lint
  - fetch-version
  - build
  - release
  - documentation
  - deploy
#
