include:
  # - local: '/analysis/sast.yml'
  - local: '/notifications/healthchecks/repo-ci-pipeline.yml'
  - local: '/notifications/pushover/repo-ci-pipeline.yml'
  # - local: '/lint/default.yml'
  # - local: '/docker/default.yml'
  - local: '/documentation/mkdocs.yml'
  # - local: '/documentation/pdf.yml'

variables:
  PUSHOVER_ID: $CI_PROJECT_TITLE

stages:
  - debug
  - lint
  - build
  - deploy
  - notify


