include:
  - local: templates/default.yml
  # - local: function/documentation/mkdocs.yml

variables:
  PUSHOVER_ID: $CI_PROJECT_TITLE
  DISABLE_SAST: "true"
  DISABLE_LINTING: "true"

stages:
  - debug
  - lint
  - build
  - deploy
  - notify

#

