include:
  # - local: '/analysis/sast.yml'
  - local: '/notifications/healthchecks-repo.yml'
  - local: '/notifications/pushover.yml'
  - local: '/lint/default.yml'
  - local: '/docker/default.yml'
  - local: '/documentation/mkdocs.yml'
  - local: '/documentation/pdf.yml'

stages:
  - debug
  - lint
  - build
  - deploy
  - notify


