include:
  - local: templates/default.yml
  - local: goss-test.yml

variables:
  PUSHOVER_ID: $CI_PROJECT_TITLE
  DISABLE_SAST: "true"
  DISABLE_LINTING: "true"

stages:
  - debug
  - lint
  - build
  - documentation
  - deploy
#

