include:
  # - local: '/analysis/sast.yml'
  # - local: '/notifications/healthchecks-repo.yml'
  - local: '/notifications/pushover.yml'
  - local: '/lint/default.yml'
  - local: '/docker/default.yml'
  # - local: '/debug/variable_match.yml'
  - local: '/pentest/sniper.yml'

stages:
  - debug
  - lint
  - build
  - notify

variables:
  PENTEST_TARGET: 192.168.1.11
  PENTEST_MODE: "stealth -o -re"
  PENTEST_REPORT: pentest-123