include:
  - local: templates/default.yml
  - local: function/repo/semantic-release.yml
  # - local: goss-test.yml

variables:
  PUSHOVER_ID: $CI_PROJECT_TITLE
  DISABLE_SAST: "true"
  DISABLE_LINTING: "true"
  DISABLE_HEALTHCHECKS: "true"
  
stages:
  - debug
  - lint
  - fetch-version
  - build
  - release
  - documentation
  - deploy
#
