branches:
  - "master"
preset: conventionalcommits
tagFormat: v${version}
repositoryUrl: https://gitlab.com/donaldrich/modular-gitlab-ci
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: test
          release: minor
        - type: ci
          release: minor
        - type: chore
          release: false
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: change
          release: patch
        - type: remove
          release: patch
        - scope: improve
          release: minor
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: fix
            section: Bug Fixes
          - type: add
            section: Added
          - type: feat
            section: Features
          - type: change
            section: Changed
          - type: remove
            section: Removed
          - type: ci
            section: Continuous Integration
            hidden: true
          - type: build
            section: Build System
            hidden: true
          - type: test
            section: Tests
            hidden: true
          - type: improve
            section: Improvements
          - type: chore
            section: Maintenance
            hidden: true
          - type: docs
            section: Documentation
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  - "@semantic-release/gitlab"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG
#       message: "chore(release): version ${nextRelease.version}\n\n${nextRelease.notes}"
