site_name: !!python/object/apply:os.getenv ["CI_PROJECT_TITLE"]
site_url: !!python/object/apply:os.getenv ["CI_PAGES_URL"]
site_description: A Collection of GitLab-CI Snippets
edit_uri: tree/master/docs

repo_url: !!python/object/apply:os.getenv ["CI_PROJECT_URL"]
repo_name: !!python/object/apply:os.getenv ["CI_PROJECT_PATH"]

nav:
  - Home: index.md
  - Quick Start: home/quick_start.md
  - Examples: home/examples.md
  - Vault Integration: home/vault_integration.md
  - Functionality:
    - Analysis: functions/analysis.md
    - Ansible: functions/ansible.md
    - Test Indent:
      - Me learning mkdocs usage: lorem.md
    - API: functions/api.md
    - AWS: functions/aws.md
    - Hashicorp: functions/hashicorp.md
    - Linters: functions/linters.md
    - Penetration Testing: functions/penetration_testing.md
    - Notifications: functions/notifications.md
  - Documentation Generation:
    - Mkdocs: mkdocs.md
    - Extensions: extensions.md
  - Links:
    - Links: links.md
    - Me learning mkdocs usage: lorem.md
  - About:
    # - Contributing &amp; Support: about/contributing.md
    # - Development: about/development.md
    - Changelog: about/changelog.md
    - Release Notes: about/release.md
    - License: about/license.md

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
  font:
    text: Ubuntu
    code: Ubuntu Mono
  features:
    - tabs
    - instant
  icon:
    repo: fontawesome/brands/gitlab
    logo: fontawesome/brands/gitlab

plugins:
  - search:
  - minify:
      minify_html: true
  - awesome-pages
  - markdownextradata: {}
  # - pdf-export
  # - simple:
  #     ignore_folders: ["tests"]

extra:
  external_links:
    functions: !!python/object/apply:os.getenv ["CI_PROJECT_URL"]
    web: !!python/object/apply:os.getenv ["CI_PROJECT_PATH"]
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/donaldrich
    - icon: fontawesome/brands/github
      link: https://github.com/donaldrich80
#       link: CI_SERVER_URL/GITLAB_USER_LOGIN

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: donaldrich
      repo: pymdown-extensions
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
  - pymdownx.tilde:
