site_name: GitLab-CI Templates
site_url: https://pages.gitlab.io/mkdocs
nav:
    - Home: index.md
    - Analysis: analysis.md
    - Ansible: ansible.md
    - API: api.md
    - AWS: aws.md
    - Hashicorp: hashicorp.md
    - Lint: lint.md
theme:
  name: material
  features:
    - tabs
    - instant
  icon:
    repo: fontawesome/brands/gitlab
    # logo: material/cloud
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.donavanaldrich.com/donaldrich/gitlab-ci-templates
plugins:
  - search:
      prebuild_index: true
  - minify:
      minify_html: true
  - awesome-pages
