site_name: Modular GitLab-CI
site_url: https://donaldrich.donavanaldrich.com/gitlab-ci-templates

repo_name: donaldrich/gitlab-ci-templates
repo_url: https://gitlab.donavanaldrich.com/donaldrich/gitlab-ci-templates

nav:
    - Home: index.md
    - Example Usage: examples.md
    - Linters: lint.md
    - Documentation Generation: docs.md
    - Analysis: analysis.md
    - Ansible: ansible.md
    - API: api.md
    - AWS: aws.md
    - Hashicorp: hashicorp.md
    - Me learning how to use Markdown: lorem.md
    - 'User Guide':
      - "Rich Markdown Pages": lorem.md
      - "Git information": lorem.md
      - "Writing macros and filters": lorem.md

theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
  font:
    text: Ubuntu
    code: Ubuntu Mono
  features:
    # - tabs
    - instant
  icon:
    repo: fontawesome/brands/gitlab
    logo: fontawesome/brands/gitlab

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.donavanaldrich.com/donaldrich

plugins:
  - search:
      # prebuild_index: true
  - minify:
      minify_html: true
  - awesome-pages
  - pdf-export
  - simple:
      ignore_folders: ["tests"]

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
