include:
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/yamllint.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/shell/all.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/markdown/all.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/json/jsonlint.yml'