include:
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/yamllint.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/markdown.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/shell/bashate.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/shell/shellcheck.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/remark-lint.yml'