include:
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/yamllint.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/markdown/markdownlint.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/shell/bashate.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/shell/shellcheck.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/markdown/remark-lint.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/json/jsonlint.yml'