include:
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/yaml.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/shell.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/markdown.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/json/jsonlint.yml'