include:
  - template: Security/Secret-Detection.gitlab-ci.yml

.secret-analyzer:
  stage: .pre
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"  
  
secret_detection:
  extends: .secret-analyzer
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"