dockerfile_lint:
  stage: lint
  image: donaldrich/function:dockerfile_lint
  allow_failure: true
  interruptible: true
  # before_script:
  #   - hadolint --version
  script:
    - dockerfile_lint -f $DOCKER_BUILD_DIR/$DOCKERFILE