include:
  # - project: 'donaldrich/gitlab-ci-templates'
  #   file: '/docker/registry.yml'

  - project: 'donaldrich/gitlab-ci-templates'
    file: '/docker/manifest.yml'

  - project: 'donaldrich/gitlab-ci-templates'
    file: '/docker/builder.yml'

  - project: 'donaldrich/gitlab-ci-templates'
    file: '/docker/builder-scripts.yml'

# variables:
#   IMAGE_TAG: latest
#   # CI_BUILD_ARCHS: "linux/arm/v7,linux/amd64"
#   DOCKERFILE: "Dockerfile"
#   DOCKER_BUILD_DIR: "."
.dockerhub:monoarch:load:
  extends:
    - .buildx:base
    - .dockerhub:registry
    - .build:monoarch:load

.dockerhub:monoarch:push:
  extends:
    - .buildx:base
    - .dockerhub:registry
    - .build:monoarch:push

.dockerhub:multiarch-concurrent:push:
  extends:
    - .buildx:base
    - .dockerhub:registry
    - .build:multiarch-concurrent:push

.dockerhub:multiarch-manifest:load:
  extends:
    - .buildx:base
    - .dockerhub:registry
    - .build:multiarch-manifest:load

.dockerhub:manifest:self:
  extends:
    - .docker:manifest:base
    - .self:registry

.dockerhub:manifest:dockerhub:
  extends:
    - .docker:manifest:base
    - .dockerhub:registry


.self:registry:
  variables:
    # REGISTRY_USER: gitlab-ci-token
    # REGISTRY_PASS: $CI_JOB_TOKEN
    # REGISTRY: ${CI_REGISTRY}
    REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG

.dockerhub:registry:
  variables:
    # REGISTRY_USER: $DOCKERHUB_USER
    # REGISTRY_PASS: $DOCKERHUB_PASS
    REGISTRY_IMAGE: $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG