include:
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/docker/registry.yml'

  - project: 'donaldrich/gitlab-ci-templates'
    file: '/docker/manifest.yml'

  - project: 'donaldrich/gitlab-ci-templates'
    file: '/docker/builder.yml'

  - project: 'donaldrich/gitlab-ci-templates'
    file: '/docker/builder-scripts.yml'

# variables:
#   IMAGE_TAG: latest
#   # CI_BUILD_ARCHS: "linux/arm/v7,linux/amd64"
#   DOCKERFILE: "Dockerfile"
#   DOCKER_BUILD_DIR: "."


.docker:dockerfile:dockerhub:
  extends:
    - .buildx:base
    - .dockerhub:registry
    - .buildx:script

.docker:url:dockerhub:
  extends:
    - .buildx:base
    - .dockerhub:registry
    - .buildx:script:url

.docker:multiarch:concurrent:dockerhub:
  extends:
    - .buildx:base
    - .dockerhub:registry
    - .buildx:multiarch-concurrent:

.docker:manifest:self:
  extends:
    - .docker:manifest:base
    - .self:registry

.docker:manifest:dockerhub:
  extends:
    - .docker:manifest:base
    - .dockerhub:registry
