healthcheck:start:
  image: donaldrich/ubuntu-runner:latest
  stage: .pre
  variables:
    GIT_STRATEGY: none
  script:
    - export VAULT_ADDR=$VAULT_ADDR
    - export VAULT_TOKEN=$VAULT_TOKEN
    # - export VAULT_TOKEN="$(vault write -field=token auth/gitlab-ci/login role=vault-reader jwt=$CI_JOB_JWT)"
    - export HEALTHCHECK_URL="$(vault kv get -field=HEALTHCHECK_URL /secret/gitlab-ci/global)"
    - export HEALTHCHECK_ENDPOINT="$(vault kv get -field=$IMAGE_NAME:$IMAGE_TAG /secret/gitlab-ci/docker-images)"
    - curl --retry 3 $HEALTHCHECK_URL/$HEALTHCHECK_ENDPOINT/start

healthcheck:end:
  image: donaldrich/ubuntu-runner:latest
  stage: .post
  variables:
    GIT_STRATEGY: none
  when: on_success
  script:
    - export VAULT_ADDR=$VAULT_ADDR
    - export VAULT_TOKEN=$VAULT_TOKEN
    # - export VAULT_TOKEN="$(vault write -field=token auth/gitlab-ci/login role=vault-reader jwt=$CI_JOB_JWT)"
    - export HEALTHCHECK_URL="$(vault kv get -field=HEALTHCHECK_URL /secret/gitlab-ci/global)"
    - export HEALTHCHECK_ENDPOINT="$(vault kv get -field=$IMAGE_NAME:$IMAGE_TAG /secret/gitlab-ci/docker-images)"
    - curl --retry 3 $HEALTHCHECK_URL/$HEALTHCHECK_ENDPOINT

healthcheck:fail:
  image: donaldrich/ubuntu-runner:latest
  stage: .post
  variables:
    GIT_STRATEGY: none
  when: on_failure
  script:
    - export VAULT_ADDR=$VAULT_ADDR
    - export VAULT_TOKEN=$VAULT_TOKEN
    # - export VAULT_TOKEN="$(vault write -field=token auth/gitlab-ci/login role=vault-reader jwt=$CI_JOB_JWT)"
    - export HEALTHCHECK_URL="$(vault kv get -field=HEALTHCHECK_URL /secret/gitlab-ci/global)"
    - export HEALTHCHECK_ENDPOINT="$(vault kv get -field=$IMAGE_NAME:$IMAGE_TAG /secret/gitlab-ci/docker-images)"
    - curl --retry 3 $HEALTHCHECK_URL/$HEALTHCHECK_ENDPOINT/fail