.lint:docker:base:
  stage: lint
  allow_failure: true
  interruptible: true
  rules:
    # - if: '$DEBUG_PIPELINE'
    #   when: never
    # - changes:
    #   - "**/Dockerfile"
    #   when: always
    - exists:
      - "**/Dockerfile"
      when: always
    - when: never

# .hadolint:
#   extends: .lint:docker:base
#   image: hadolint/hadolint
#   before_script:
#     - echo $DOCKERFILE
#     - echo $DOCKER_BUILD_DIR
#     - hadolint --version
#   script:
#     - hadolint "$DOCKER_BUILD_DIR/$DOCKERFILE"

hadolint:lint:
  # extends: .lint:docker:base
  stage: lint
  image: hadolint/hadolint
  allow_failure: true
  interruptible: true
  before_script:
    - echo $DOCKERFILE
    - echo $DOCKER_BUILD_DIR
    - hadolint --version
  script:
    # - cat $DOCKER_BUILD_DIR/$DOCKERFILE
    - hadolint $DOCKER_BUILD_DIR/$DOCKERFILE

projectatomic:lint:
  # extends: .lint:docker:base
  stage: lint
  allow_failure: true
  interruptible: true
  image: projectatomic/dockerfile-lint
  # before_script:
  #   - echo $DOCKERFILE
  #   - echo $DOCKER_BUILD_DIR
  script:
    # - cat "$DOCKER_BUILD_DIR/$DOCKERFILE"
    - dockerfile_lint --permissive -f $DOCKER_BUILD_DIR/$DOCKERFILE

.dockerfilelint:
  # extends: .lint:docker:base
  allow_failure: true
  interruptible: true
  image:
    name: replicated/dockerfilelint
    entrypoint: [""]
  before_script:
    - dockerfilelint --version
    # - echo $DOCKERFILE
    # - echo $DOCKER_BUILD_DIR
  script:
    # - cat $DOCKER_BUILD_DIR/$DOCKERFILE
    - dockerfilelint "$DOCKER_BUILD_DIR/$DOCKERFILE"