include:
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/ssh/default.yml'

remove-unused-images:
  extends: .ssh-runner
  stage: .post
  # when: delayed
  # # start_in: 1 minute
  script:
    - ssh $SSH_USER@$SSH_ADDRESS -i ~/.ssh/$DEPLOYMENT_KEY -p $SSH_PORT "docker image prune --all --force"
