dockerfilelint:
  stage: lint
  image: donaldrich/function:dockerfilelint
  allow_failure: true
  interruptible: true
  # before_script:
  #   - hadolint --version
  script:
    - dockerfilelint $DOCKER_BUILD_DIR/$DOCKERFILE
  rules:
    - if: '$DISABLE_LINTING == "true"'
      when: never
    - when: on_success