include:
  - local: function/notifications/pushover/repo-ci-pipeline.yml
  - local: function/docker/default.yml

.build:functions:
  retry: 2
  interruptible: true
  extends:
    - .buildx:base
    - .dockerhub:registry
    - .build:monoarch:push

.generate-function-doc:
  image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/secrets/private/docker-runner:latest
  variables:
    GIT_STRATEGY: none
    VERSION_COMMAND: --version
    HELP_COMMAND: --help
  retry: 2
  stage: documentation
  script:
    - apk add curl jq
    - docker pull donaldrich/function:$IMAGE_TAG
    - docker run --rm donaldrich/function:$IMAGE_TAG $HELP_COMMAND
    - docker run --rm donaldrich/function:$IMAGE_TAG $HELP_COMMAND > $CI_PROJECT_DIR/docs/snippets/config/$IMAGE_TAG.md
    - docker run --rm donaldrich/function:$IMAGE_TAG $VERSION_COMMAND > $CI_PROJECT_DIR/docs/snippets/version/$IMAGE_TAG-docker.md || true
    - curl -u $GITHUB_ID:$GITHUB_SECRET https://api.github.com/repos/$REPO_URL > $CI_PROJECT_DIR/docs/snippets/github-info/$IMAGE_TAG.md || true
    - cat $CI_PROJECT_DIR/docs/snippets/github-info/$IMAGE_TAG.md | jq --raw-output ".description" > $CI_PROJECT_DIR/docs/snippets/description/$IMAGE_TAG.md || true
    - docker image inspect donaldrich/function:$IMAGE_TAG --format='{{.Size}}' > $CI_PROJECT_DIR/docs/snippets/image-size/$IMAGE_TAG.md || true
    - docker image inspect donaldrich/function:$IMAGE_TAG | jq . > $CI_PROJECT_DIR/docs/snippets/image-info/$IMAGE_TAG.md
    - docker history donaldrich/function:$IMAGE_TAG > $CI_PROJECT_DIR/docs/snippets/layers/$IMAGE_TAG.md || true


cache:
  # untracked: true
  paths:
    - docs/snippets/

stages:
  - debug
  - lint
  - dependency
  - build
  - test
  - push
  - documentation
