site_name: Modular GitLab-CI
site_url: https://pages.gitlab.io/mkdocs
# nav:
#     - Home: index.md
#     - Examples: examples.md
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
  font:
    text: Ubuntu
    code: Ubuntu Mono
  features:
    - tabs
    - instant
  icon:
    repo: fontawesome/brands/gitlab
    # logo: material/cloud
repo_name: repo_name
repo_url: repo_url
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: link
plugins:
  # - search:
      # prebuild_index: true
  - minify:
      minify_html: true
  - awesome-pages
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: Link
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde