.self:registry:
  variables:
    # REGISTRY_USER: gitlab-ci-token
    # REGISTRY_PASS: $CI_JOB_TOKEN
    # REGISTRY: ${CI_REGISTRY}
    REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG

.dockerhub:registry:
  variables:
    # REGISTRY_USER: $DOCKERHUB_USER
    # REGISTRY_PASS: $DOCKERHUB_PASS
    REGISTRY_IMAGE: $CI_PROJECT_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG
