.ssh-provision: &ssh-provision
- git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@$SECRET_REPO ~/secrets
- mkdir -p ~/.ssh
- chmod 700 ~/.ssh
- cp -r ~/secrets/ssh/. ~/.ssh
- chmod 0600 -R ~/.ssh
- chmod 700 ~/.ssh
- eval $(ssh-agent -s)
- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

.ansible-runner:
  image: donaldrich/ansible:latest
  before_script:
    - *ssh-provision
    - cp -r ~/secrets/ansible-inventory inventory
    - ansible-galaxy install --roles-path .ansible/roles -r requirements.yml
  after_script:
    - rm -r ~/secrets
    - rm -r ~/.ssh
  variables:
    ANSIBLE_CONFIG: "ansible.cfg"
    # ANSIBLE_HOST_KEY_CHECKING: "false"
    # ANSIBLE_RETRY_FILES_ENABLED: "false"
    # ANSIBLE_FORCE_COLOR: "true"
    #    ANSIBLE_VAULT_PASSWORD_FILE: ./vault.key