pages:
  stage: deploy
  image:
    name: donaldrich/function:mkdocs
    entrypoint: [""]
  script:
  - mkdocs build
  - mv site pages
  artifacts:
    paths:
    - pages
  # only:
  # - master
  rules:
    - exists:
      - "mkdocs.yml"
      when: on_success
    - when: never