pages:
  stage: deploy
  image:
    name: donaldrich/function:mkdocs
    entrypoint: [""]
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  # only:
  # - master
  rules:
    - exists:
      - "mkdocs.yml"
      when: on_success
    - when: never
    
    
    # http://domain.com/__purge_cache?zone=%5Bzone_id%5D