include:
  - project: donaldrich/gitlab-ci-templates
    file: function/lint/yaml.yml
  - project: donaldrich/gitlab-ci-templates
    file: function/lint/shell.yml
  - project: donaldrich/gitlab-ci-templates
    file: function/lint/markdown.yml
  - project: donaldrich/gitlab-ci-templates
    file: function/lint/json/jsonlint.yml